# Application 1

## Membres du groupe


1.   GUIDIBI Teddy
2.   JALAL Alaeddine
3.   KHATIB Asmaa
4.   MONKOUN Aris
5.   ROUDRI Chaimae

## With Sympy

In [130]:
import sympy as sp
import numpy

In [131]:
w=sp.symbols('w')
x=sp.symbols('x')
b=sp.symbols('b')
y=sp.symbols('y')

In [132]:
l=(sp.exp(numpy.dot(w,x) + b) -y)**2

In [133]:
l

(-y + exp(b + w*x))**2

$$
\frac{\partial l}{\partial w}
$$

In [134]:
sp.diff(l,w)

2*x*(-y + exp(b + w*x))*exp(b + w*x)

$$
\frac{\partial l}{\partial x}
$$

In [135]:
sp.diff(l,x)

2*w*(-y + exp(b + w*x))*exp(b + w*x)

$$
\frac{\partial l}{\partial b}
$$

In [136]:
sp.diff(l,b)

2*(-y + exp(b + w*x))*exp(b + w*x)

## With Torch

In [137]:
import torch

In [138]:
torch.manual_seed(42) 

In [139]:
w = torch.linspace(-4,4,10, dtype=torch.float32, requires_grad=True)
w

tensor([-4.0000, -3.1111, -2.2222, -1.3333, -0.4444,  0.4444,  1.3333,  2.2222,
         3.1111,  4.0000], requires_grad=True)

In [140]:
x = torch.linspace(-1,1,10, dtype=torch.float32, requires_grad=True)
x

tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000], requires_grad=True)

In [141]:
b = torch.linspace(1,2,1, dtype=torch.float32,requires_grad=True)
b

tensor([1.], requires_grad=True)

In [142]:
y = 1

### Graph

In [143]:
l0 = torch.matmul(w,x)

In [144]:
l1 = l0 - b

In [145]:
l2 = torch.exp(l1)

In [146]:
l3 = l2 - y

In [147]:
l = l3 ** 2

### BackPropagation

In [148]:
l.backward()

In [149]:
print(b.grad)

tensor([-3.8657e+13])


In [150]:
print(x.grad)

tensor([-1.5463e+14, -1.2027e+14, -8.5904e+13, -5.1542e+13, -1.7181e+13,
         1.7181e+13,  5.1542e+13,  8.5904e+13,  1.2027e+14,  1.5463e+14])


In [151]:
print(w.grad)

tensor([-3.8657e+13, -3.0066e+13, -2.1476e+13, -1.2886e+13, -4.2952e+12,
         4.2952e+12,  1.2886e+13,  2.1476e+13,  3.0066e+13,  3.8657e+13])
